# Generated by Django 4.2.7 on 2026-01-20 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('descricao_curta', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('jogadores_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('jogadores_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('tempo_min', models.IntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (25, '25 min'), (30, '30 min'), (35, '35 min'), (40, '40 min'), (45, '45 min'), (50, '50 min'), (60, '60 min'), (80, '80 min'), (100, '100 min'), (120, '120 min'), (140, '140 min'), (180, '180 min'), (200, '200 min'), (240, '240 min'), (300, '300 min'), (360, '360 min')])),
                ('tempo_max', models.IntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (25, '25 min'), (30, '30 min'), (35, '35 min'), (40, '40 min'), (45, '45 min'), (50, '50 min'), (60, '60 min'), (80, '80 min'), (100, '100 min'), (120, '120 min'), (140, '140 min'), (180, '180 min'), (200, '200 min'), (240, '240 min'), (300, '300 min'), (360, '360 min')])),
                ('idade_recomendada', models.IntegerField(choices=[(2, '2+'), (4, '4+'), (6, '6+'), (8, '8+'), (10, '10+'), (11, '11+'), (12, '12+'), (14, '14+'), (16, '16+'), (18, '18+')])),
                ('peso', models.FloatField(default=0.1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('componentes', models.ManyToManyField(blank=True, to='app.componente')),
                ('mecanicas', models.ManyToManyField(blank=True, to='app.mecanica')),
                ('temas', models.ManyToManyField(blank=True, to='app.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Glossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100)),
                ('definicao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='glossario/')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='EstruturaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FASE', 'Fase'), ('ACAO', 'Ação'), ('RODADA', 'Rodada')], max_length=10)),
                ('ordem', models.IntegerField(default=1)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CondicoesVitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='CondicoesEspeciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estruturajogo')),
            ],
        ),
        migrations.CreateModel(
            name='CondicoesDerrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo')),
            ],
        ),
    ]
